#spring.application.name=ProductMicroservice
server:
  port: 60143
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      #      retries: 10
      properties:
        enable:
          idempotence: true
        retry:
        #          backoff:
        #            ms: 1000
        linger:
          ms: 0
        delivery:
          timeout:
            ms: 20000
        request:
          timeout:
            ms: 10000
        max:
          in:
            flight:
              requests:
                per:
                  connection: 6
  application:
    name: 'product-microservice'
