#  spring.application.name=email-notification-microservice
server:
  port: 0
spring:
  application:
    name: 'email-notification-microservice'
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


